//
// Types for files generated by the Tiled Map editor (http://www.mapeditor.org/)
//
//
declare namespace TiledMap {
  type TileId = number
  type TileIdString = string

  interface Map {
    height: number,
    width: number,
    layers: Layer[],
    orientation: 'orthogonal',
    renderorder: 'right-down',
    tilesets: TileSet[],
    tilewidth: 32,
    version: string,
  }

  interface Layer {
    data: TileId[],
    height: number,
    name: string,
    opacity: 1,
    type: "tilelayer",
    visible: boolean,
    width: number,
    x: 0,
    y: 0,
  }

  interface TileSet {
    name: string,
    columns: number,
    firstgid: number,
    image: string,
    imageheight: 701,
    imagewidth: 672,
    margin: number,
    spacing: number,
    tilecount: number,
    tileheight: number,
    tilewidth: number,
    tiles: Record<TileIdString, undefined | TileDef>
  }

  type TileDef = { type: "wall" }

  interface TileProperties {
    wall: boolean
  }
}
