
[[player]]
id = "alice"
password = "abc"
name = "Alice"
size = 25
currentHp = 30
maxHp = 30
pos = { x = 3, y = 3 }
skills = ["melee-attack", "singe", "wind-up-punch"]

[player.stats]
con = 10
dex = 10
int = 10
mov = 10
str = 10
wis = 10


[[player]]
id = "bob"
password = "xyz"
name = "Bob"
size = 25
currentHp = 30
maxHp = 30
pos = { x = 2, y = 7 }
skills = ["melee-attack", "singe", "wind-up-punch"]

[player.stats]
con = 10
dex = 10
int = 10
mov = 10
str = 10
wis = 10
