
[[skill]]
name = "melee-attack"
description = """
  Nothing feels better than a good old punch in the face.
"""
range = 1
cost = 0
time = { startup = 0.5, cooldown = 0.5, recharge = 1 }
target = { type = "single", valid = "enemy" }

[[skill.effect]]
type = "damage"
amount = 2
scale = { str = 1 }



[[skill]]
name = "singe"
description = """
  Singe your enemy with a quick magic strike.
"""
range = 2
cost = 0
time = { startup = 0.25, cooldown = 0, recharge = 4 }
target = { type = "single", valid = "enemy" }

[[skill.effect]]
type = "damage"
amount = 2
scale = { mag = 1 }



[[skill]]
name = "fumes"
description = """
  Cause blindness in an area of effect.
"""
range = 4
cost = 0
time = { startup = 0.5, cooldown = 1, recharge = 12 }
target = { type = "radius", size = 50, affects = "all" }

[[skill.effect]]
type = "blind"
amount = 0.25
duration = 8



[[skill]]
name = "mend"
description = """
  Mend a bit of health of one of your allies.
"""
range = 6
cost = 0
time = { startup = 0.5, cooldown = 0.5, recharge = 5 }
target = { type = "single", valid = "ally" }

[[skill.effect]]
type = "heal"
amount = 5
scale = { mag = 0.25, wis = 1 }
